### ISSUE TITLE
Space Lube.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1673]
To put it short and sweet, Space Lube has a tendency to not properly apply itself to floors when using a spray bottle (could be the same story with other containers as well) both with 5u and 10u, It will sometimes simply not apply itself onto a tile to create a slippery surface and instead simply disappear.

**Comment by Carbonhell** [comment]
You need minimum 10 units to make a tile wet, if you use less than 10 nothing happens, it's a feature to avoid mass lubing, 10 units work correctly from what i tested in local,you probably had something like only 9 units left,sprayed them with 10 units and nothing happened due to not having 10 units of lube

**Comment by Carbonhell** [comment]
Not an issue, close?

**Comment by ghost** [comment]
It seems that this may be more of a balance or tweaking concern. I've done some more experiments and It seems that space lube can absolutely REFUSE to apply itself (and other chemicals in sprayers) properly onto for example, floors if there are other objects on top of the floor tile. No matter how tiny or insignificant, they can completely block your ability to apply lube even though you have a clear view of the floor and is clicking on it.

**Comment by Pyko1** [comment]
Possibly due to some sprayed lube getting added to mob/obj?
Feature?

**Comment by Pyko1** [comment]
feature
