### ISSUE TITLE
Suicide Bug

### ISSUE THREAD

**Issue by AliiTea** [HippieStationArchive/HippieStation13-1#1954]
Can't suicide while inside a disposal unit.

It still gives the suicide message but you only take minimal damage and don't get the "Has commited suicide" when you are examined

**Comment by 24twelve** [comment]
I tried to fix this bug.
But I could not reproduce it. I checked locally on this commit. (https://github.com/HippieStationCode/HippieStation13/commit/8737818c3ea39482e75563b3203cd10ea3b8a398)

**Comment by Carbonhell** [comment]
It might be relevant to the item you used to suicide. Someone fucked up a long time ago and instead of returning a define like BRUTELOSS or FIRELOSS he returned damtype, through most of those bugs were fixed some items may've been skipped so if you remember what item you had inhand that could be helpful

**Comment by AliiTea** [comment]
jumped inside a disposals bin with assistant gear and a fireaxe on my back, typed suicide with nothing in hands and only took enough oxyloss to passout and come back

**Comment by 24twelve** [comment]
Too strange, I succesfully suicided with bare hands in disposals.
Maybe your character had some healing chemicals in the bloodstream?

**Comment by AliiTea** [comment]
Hmm...

**Comment by AliiTea** [comment]
yup @24twelve you were correct
