### ISSUE TITLE
Changeling Hive Absorb doesn't function

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1995]
You successfully absorb the DNA but the genome doesn't appear in the selection box for transformation.

**Comment by JohnGinnane** [comment]
I've had a look at this, and it seems to be failing on line 369 in https://github.com/HippieStationCode/HippieStation13/blob/a26dfc4b9060e0ccc0d7beec4c509743d8693f05/code/game/gamemodes/changeling/changeling.dm

Due to undefined variable "real_name". I tried debugging it and I'm not sure if the hivemind_bank is a list containing human objects or "profiles" if what the difference is between them. Does anyone have any ideas?

**Comment by JohnGinnane** [comment]
Okay I've fixed it on my local copy. People who you've already absorbed via hive will still appear in the list but selection is checked against your stored profiles' names

https://github.com/HippieStationCode/HippieStation13/pull/2006

**Comment by Pyko1** [comment]
fixed
