### ISSUE TITLE
Fix identity banning

### ISSUE THREAD

**Issue by Lawligagger** [HippieStationArchive/HippieStation13-1#2019]
https://www.youtube.com/watch?v=Cy4-snbDcIM

it ain't working apparently

**Comment by Carbonhell** [comment]
Banning works but when round restart the info somehow gets lost:

/proc/appearance_isbanned returned: null

even through banning panel says that the ban is there. might be because there's no proc that collects the info from the database from what i can see.

**Comment by Carbonhell** [comment]
checked today, the banning list gets currently queried from the database, but for some reasons the isbanned proc returns a weird value:
/proc/appearance_isbanned returned: rbonhell
that was tested with my ckey, maybe the issue is here? var/startpos = findtext(s, "## ") + 3 through there's no ## before my name so.

**Comment by Carbonhell** [comment]
Apparently somehow fixed it,except the reason which still comes out weirdly as part of the ckey.

**Comment by Carbonhell** [comment]
Fixed
