### ISSUE TITLE
Rework/Look into Reviver Implants?

### ISSUE THREAD

**Issue by Jsau7** [HippieStationArchive/HippieStation13-1#2856]
I usually get top tier Research levels when playing as a Research-Based job, But one thing I've noticed is how Reviver implants aren't exactly very helpful.
When I get the levels to make and implant one (If The Shuttle isn't called early), When I get into crit it usually just leaves me in the state of crit limbo, Not too out of crit or too into crit, But it doesn't really do anything to stop the bleeding, So if it's supposed to keep someone alive, what's the point if you'll just bleed to death? No wonder Sydnies never buy this.

**Comment by Kierany9** [comment]
Yeah they're complete garbage. Although git isn't for balancing issues, this might be worth a look at because they don't even do their job properly and have an extremely misleading description.

>This implant will attempt to revive you if you lose consciousness.

This implies that they actually help recover consciousness faster from things like explosions, sleep chems and the like,, when in reality they just have extremely poor healing when you're in crit.

**Comment by ArcLumin** [comment]
Has been reworked, please close
