### ISSUE TITLE
Point blank shots with projectile weapons deal no damage

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2914]
Point blank shots with projectile weapons appear to do no, or severely reduced damage. Issue reported by IvanTheCracka originally, and I ran a couple tests of my own.

**Comment by ArcLumin** [comment]
Seems to work fine with me

**Comment by LilKek450** [comment]
I tested it. Not even a fucking .44 does more than 75 brute when aimed to the leg. I can understand that it doesnt do as much brute because there are no vital organs, but it at least should cripple or something. This first happened to me when i slipped the hop and unloaded my revolver on her. It didnt kill her or slow her down and she got right up and murdered me.

**Comment by ArcLumin** [comment]
Ah, the issue wasn't properly explained. If I recall, for non chest/head areas, the max damage for one body part is 75. So working as intended, its only hitting one body part and not a vital one.
