### ISSUE TITLE
*facid is op

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-1#3400]
over the past couple of rounds a specific shitter used facid to melt people's shit with little to no justification

one 100u beaker is enough to destroy everything but a person's pda and id and leave them with nothing, and they were taking advantage of that to deprive people of their stuff

it's the equivalent of stripping someone of everything but their id or pda and spacing their shit, except it happens immediately and the recipe is quick to make

**Comment by ArcLumin** [comment]
We don't have poly acid my dude

But Facid is what that guy was using, and two 100u beakers of it to deprive them. It's bullshit but yeah

**Comment by cacogen** [comment]
i forgot it was changed years ago
i never bothered to learn new chem

it's always been shit yeah but is it worth it?

**Comment by ArcLumin** [comment]
Lots of higher class armors won't be acided by it. You need a shitton of it to actually get most stuff off, so beakersplashing is the only really good method for it. And there's significantly more op shit to splash on people.

**Comment by cacogen** [comment]
yeah but the issue is using it to destroy people's stuff without getting banned
most characters don't have the armour necessary to combat it and if you splash worse stuff on people you'll get banned

**Comment by ghost** [comment]
Not really that OP. 50u is enough to melt jumpsuits and bags, but not a simple labcoat and some other jackets. 80u is able to melt most jackets, but not hardsuits. No amount of acid will melt IDs, PDAs, or the contents inside of containers such as your bag or pockets. Also, most popular ruling with headmins seems to be that anything not involving attacking crew when implanted, betraying team members in team antag modes, or critting non-antags as a non-antag is IC. Mildly inconveniencing another player is hardly ban worthy.

**Comment by ArcLumin** [comment]
Getting your shit destroyed sucks, especially since it can destroy your ID. And shoes.

But yeah, if your ID isn't in your PDA, you can say goodbye to it.

**Comment by ghost** [comment]
I've splashed an op with 80u of it, which is pretty much at the "fuck your shit" level, and had a PDA drop unharmed. May have just been a fluke though.

**Comment by ghost** [comment]
Biggest thing to note here is that nobody actually uses facid. Like, ever. I think the two or three rounds of the acid man was the first time I've seen it used for anything but barnyard curse removal since before the rebase. Even research doesn't use it for opening crates, they just autistically pour sulpheric acid on them until they open.

**Comment by ArcLumin** [comment]
Mostly because the acid shit was so nerfed it needs to be in large amounts to properly remove shit.

But when it does, it can destroy guns, ammo, all sorts of shit. Enough and it will melt your backpack and everything in it (but I've only seen that in bluespace beakers of it)

**Comment by ghost** [comment]
Even when it was in its prime, as polyacid, it wasn't used too much. Come to think of it, the two big times that polyacid has been used to great effect were by me. It's just easier to beat people to death, more destructive to make bombs, and most chemists just poison people. It's a niche chem that's only ever used to remove cursed equipment, and even then most people forgot it exists and use sulpheric acid instead. Very, very rarely is it used offensively, because doing so requires both a lot of setup and coming to terms with the fact that you'll probably end up getting lynched very soon.

**Comment by ghost** [comment]
I think a nerf was brought up at one point, but rejected due to poly being one of the few things on station (at the time) that could completely and utterly fuck up a team of careless nuke ops or death squad commandos.

**Comment by cacogen** [comment]
@QuarianCommando 
>I think the two or three rounds of the acid man

You, you mean.

>Mildly inconveniencing

I don't think you honestly believe it's a mild inconvenience to lose all your clothes, bag and items. Especially if the HoP isn't in their office (which they usually aren't, especially later in the shift).

>Even when it was in its prime, as polyacid, it wasn't used too much

It was used all the time as sprays on /tg/station. To the point they chose to make it impossible to put in spray bottles.

>because doing so requires both a lot of setup 

It doesn't take long to make at all. All of the ingredients are available straight out of the chem dispenser (i.e. no compounds are needed).

>and coming to terms with the fact that you'll probably end up getting lynched very soon.

You didn't get lynched when you did it. Nobody cared. It only bothers the people you do it to.

**Comment by ghost** [comment]
So? Being mad doesn't change the fact that it's a niche chem that's almost never used, and has its place as a tool to remove cursed items, as well as disarming a team of nuke ops if people would actually bother to make something as chemist other than carpet and drugs.

Being mad that someone did something different for a few rounds doesn't mean that code should be removed, or unnecessarily nerfed. 

Also, don't discount the effort that I put into acid man. Chemist dragging around a 1000u tank of facid behind them and darting between shadows isn't something you see often.

**Comment by yobob591** [comment]
no pls

Acid was already nerfed to hell, no need to make it utterly useless. If anything make people who do this shit valid and call it a day

**Comment by ghost** [comment]
People who acid are already valid. Every time I've used acid, I've been valid and killed for it. It was an hour and a half ago and this guy is still throwing a fit over it, to the point where he's bitching at coders to nerf it.

**Comment by cacogen** [comment]
It should be harder for people like QuarianCommando to walk into chemistry and make it to throw on the crew.

The recipe is literally just:

1 part Fluorine
1 part Hydrogen
1 part Potassium
1 part Sulphuric Acid

Maybe it could be more time-consuming to make?

>Every time I've used acid, I've been valid and killed for it.

This is yet another lie. Neither round I saw you throwing acid were you killed.

**Comment by yobob591** [comment]
Acid doesn't need a nerf period fam, it's hardly useful for anything but fucking with people and maybe destroying weapons

**Comment by ArcLumin** [comment]
and breaking open lockedboxes

**Comment by cacogen** [comment]
>Acid doesn't need a nerf period fam

Yeah, it does. It's too easy to use it to ruin people's rounds. Getting crit is preferable to losing all your items. At least one is temporary.

**Comment by ghost** [comment]
I distinctly remember dying during two of them. One of them I was saved by someone with a sense of humor, melted all his shirt for giggles, then got memed on. The other once, I stole an ops minibomb and suicide bombed him with it. Can't remember the last round, but I probably died then too.

**Comment by ghost** [comment]
Also, you need to heat it too.

**Comment by Swagile** [comment]
intended behavior, robust the nerdo instead of trying to nerf acid

quarian put it nicely when you can just get a taser near round start and do this exact same thing except with stripping people and you'd ruin their round just as badly as using facid. stun + cuff + taking your shit, putting it in your backpack / lockering it, then running away is just as bad as facid

**Comment by blobbernaut** [comment]
a beaker full of clf3 will probably just kill you so thank them for not using that

**Comment by ghost** [comment]
Speaking of clf3, I remember splashing it on a wall and having the wall just instantly disappear. Was that indented behavior that got patched out, or a bug? I can't do it anymore.

**Comment by ArcLumin** [comment]
Uh, you sure that was our code base? I've never heard of this, and I've splashed walls with CLF3

**Comment by ghost** [comment]
It was. It only worked the first time I tried it, but not after that. Must have been a really early bug/feature that was removed.

**Comment by Kierany9** [comment]
solution:

ban he

**Comment by doobiedoo23** [comment]
You should have been banned for aciding people as a non antag, nice admins :^)

**Comment by Carbonhell** [comment]
Did you guys go full retard?
If you melt someone's shit as nonantag expect to be banned. It isn't a balance issue, it is at most an administrative issue if the acid fucker wasn't an antag.

**Comment by ghost** [comment]
Making the chemical more complex to make doesn't change jack shit. More complex chem recipes is an awful balance method.
If you're going out of your way to acid and destroy everyone's shit then you can expect catbans.  If you get acided and lose your headset and gloves or something, deal with it ICily.

**Comment by ghost** [comment]
So can someone in administration actually come out and make a ruling on when the whole not intervening unless someone is in crit bullshit somehow magically ceases to apply? Or is this another one of those things where you're either clear or completely fucked depending on which headmin gets the most involved?

**Comment by ghost** [comment]
It all depends on the circumstances. Admin policy is to minimise intervention if players can do IC reactions towards IC actions and provided IC actions to begin with aren't _too_ out of line.

**Comment by ghost** [comment]
If the team has decided to actually do their jobs and moderate the server, maybe that decision could have been made a year ago, before the server turned into grief station, instead of arbitrarily deciding that you prefer method A of being a shit over method B and handing out bans to only half the shitters with no real policy behind it?

**Comment by ghost** [comment]
You want the rules to be utterly set in stone so everyone has to read a 20 page document on how to play which is updated whenever we find a new grey area scenario?
The game is always gonna have grey areas which is up to the admins to dispute.

**Comment by ghost** [comment]
No, I want the rules to be set in stone so players have to read a one page document, and don't have to worry about being banned because the present headmin has some personal issue with whatever they're doing, while allowing some other shit stain to do similar or worse while parroting "IC issue" in every ahelp.

**Comment by ghost** [comment]
And even more wonderful, it would get rid of the special snowflake shitters being able to suck up to their favorite big daddy headmin anytime something goes wrong and either get them to rule in their favor out the door, or have whatever ban they get reversed for them.

**Comment by ghost** [comment]
I haven't even been on to witness this individual. I don't even know who's doing it.

**Comment by ghost** [comment]
I did it. I'm still awaiting my ban for mildly inconveniencing a few people for a couple rounds, while chefferz gets to throw his weight around the admin team's decisions despite being permabanned, because I haven't found a headmin's ass to bury my head in.

**Comment by ghost** [comment]
The fuck does chefferz have to do with this?

**Comment by ghost** [comment]
Every single player who sucks up to a headmin, knowing full well that their particular favored admin will rule in their favor, is a problem. Because the server has minimal concrete rules, all I would have to do to guarantee getting off scott free is test the waters during each headmin's shift and see who would let me get away with the most, which is why the server is such a grief fest. Chefferz was just an example, and more of a personal attack, seeing as you're second on the list of people he rattles off whenever something doesn't go his way.

**Comment by dreamcrab** [comment]
just go kill the guy if he melts all your shit??? act like antag get treated like one

**Comment by blobbernaut** [comment]
Drama

**Comment by ghost** [comment]
I think currently chefferz hates my guts due to our differences?
Anyway, I never ruled in chefferz favour from IC shit, OOC shit was either or depending on the situation.

And to finalise, concrete rules that cover everything will never happen because it's impossible with a game of this scale. Teaching admins on how to evaluate situations is the more possible solution to this. Do note that unforunately there are admins who just follow the policy and the rules rather than the intent of the rules, all of which are derived from the holy grail of rule 1.

If you're being a cunt for the purpose of being a cunt then chances are, you'll be banned. Splashing acid on someone can range in terms of severity and can be justified depending on the situation. No rule set is gonna cover exactly when and why you're justified to splash with acid because it's a near infinite list to consider.

**Comment by ArcLumin** [comment]
1u of this chat is more acidic than facid

**Comment by Spacedong** [comment]
lmao close this

**Comment by KayeArray** [comment]
pjsalt

**Comment by cacogen** [comment]
Well, I think you gave Quarian what he wanted by closing this after he shit it up with stuff unrelated to the issue. So thanks for that.

Also, a couple of people weighed in with dumb arguments I didn't get to reply to before this was closed. Just be smart 🤓

**Comment by Pyko1** [comment]
we have quite a few other balance issues open and there is no harm about disgussing it.

**Comment by KayeArray** [comment]
It's not.

**Comment by GuyonBroadway** [comment]
It's annoying and it's use y non-antags on other non-antags is a matter for debate as it weather or not it's an IC issue or a bannable offence. But balance wise it's not too terrible, you can use it to pull some tricky dickey shit with lock-boxes and ruin some peoples days but as it stands it's no worse than anything else you can make.

**Comment by Pyko1** [comment]
Main issue with acid is that it leaves you alive.

With all your shit melted you are worse off than a fresh spawn, if the chemist had murdered you could at least ahelp it, with no issues.
The problem is is it just an "IC issue deal with it" or "being a dick" if you just go chem to splash random people 4noraisins as nonantag.

I do recall billy bear got thiniced and chem banned for aciding people as nonantag.
Also could make it procude less acid, to make it take at least slightly more effort to pour acid on everyone.

**Comment by cacogen** [comment]
rip
