### ISSUE TITLE
HoS can be antag via wizard summon guns.

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-1#363]
HoS and probably Captain and security can become antags from this. This shouldnt be a thing

**Comment by SplergeBucket** [comment]
P'sure this is a feature in which everyone has a chance of becoming a survivor, i'm fine with this.

**Comment by Kokojos** [comment]
Same here. Discussion should be done between headmins, but IMO, it's fine like this.

**Comment by Weisyl** [comment]
Personally I don't like anyone becoming a survivor, but at the least, anyone who's implanted shouldn't become one. That way, you have someone who you can probably trust more than anyone else.

**Comment by collinxchu** [comment]
If it's a huge deal, just seperate Summon Guns and Summon Survivors.
Keep guns as is but have antags cost a point instead of giving one, as I suggested in skype a few days ago. 

The point of "raising the stakes" is to make life harder in exchange for another spell, but it's more typically used to make their lives easier by having the crew kill one another/give more guns to the wiz in the long run.

Alternatively have implanted jobs be immune to becoming a survivor if you don't want to change how it works. Or both!
