### ISSUE TITLE
Medbay is literally all R-Walls

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#403]
Completely surrounded by them too, I get that we had a problem with people breaking into Medbay from the lobby, but why has it become one of the most secure places on the station? Not even Science or the Bridge is all R-Walls

**Comment by Nokington** [comment]
Feature

**Comment by Jaygriff** [comment]
Because shitlers like breaking in rather than waiting a few seconds.

**Comment by WhiteFox08** [comment]
Forces medics to actually do their job.

**Comment by SplergeBucket** [comment]
It's a shitty supplement reinforcing walls that people break into to make the station ~better~.
It was good how it was before.

**Comment by Jaygriff** [comment]
It was clearly not good or we wouldent have changed it. 
Medics had no chance to do their jobs because people were walking in every 2 minutes and breaking down whatever window was in the way and taking what they want. The sleepers were to combat the minor injuries while the waiting room deals with the rest.

**Comment by collinxchu** [comment]
medbay being easy to break into is dicks.

medbay being the hardest thing to break into is also dicks. At most you want the main entrances reinforced + CMO and that's it.

**Comment by collinxchu** [comment]
Will do up a fix once Lcass chem is finished - hopefully in the next few days.

**Comment by whitefox08** [comment]
Fixed in #459
