### ISSUE TITLE
Gygax AC10 harms the user

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#694]
the gygax ac10 can harm the user by walking into its own bullets.. tf

**Comment by Weisyl** [comment]
This seems to be part of a larger issue where all mech weapons that fire multiple projectiles per click end up shooting them all at the same time, leading to all the projectiles getting stuck on the firer's tile. This doesn't happen with the AC2 most likely because it fires only 3 projectiles - but this still needs some more investigation. Can look into it later.

**Comment by ghost** [comment]
i was normal walking too, no leg actuators but i bet that'd probably break some shit if you engaged them whilst shooting forward
