### ISSUE TITLE
Some things wrong with constructs

### ISSUE THREAD

**Issue by CreationPro** [HippieStationArchive/HippieStation13-1#74]
Bug details:

Constructs are fucked in a variety of ways.
1. Flashbang a construct. Wham, deaf forever.
2. Artificers get auto-muted and can't mend, gg.
3. Alien toys try to leap at constructs' faces.

How to reproduce:
1. Flashbang a construct. Shazam, never hears again.
2. Mend yourself a lot. WHAM, muted.
3. Place an alien toy near construct. It tries to hug you but it can't. You have no proper face.

Notes: I had such a bad time because of these two, holy shit

**Comment by SplergeBucket** [comment]
First issue is still a problem.
Second has been fixed.
Can't confirm the third one.

**Comment by SplergeBucket** [comment]
Second one is not fixed, fucking constructs can still be muted for repairing stuff amongst other things.

**Comment by Chronitonity** [comment]
Issue one is a problem with how mob code works, im fairly certain constructs are simple mobs or something around that, which don't get their ears healed over time.

Issue two has been here forever, and its because healing spams chat or something, shouldn't be too hard to fix if someone who knows what theyre doing looks at it

Issue three isn't a huge deal, who cares that an alien toy jumps at you, it doesn't break anything.
