### ISSUE TITLE
Game ends with shadowlings being cloned.

### ISSUE THREAD

**Issue by killer653** [HippieStationArchive/HippieStation13-1#95]
Game will auto-end if shadow lings are being cloned.
http://puu.sh/hl8wE/29675b783d.png

Photo depicts a me cloning a shadowling and the game saying it is "dead" even though it is being cloned.

**Comment by lcass** [comment]
Feature , because the shadow ling died in the first place.
SHADOWLING: A gamemode based on previously-run events

Aliens called shadowlings are on the station.
These shadowlings can 'enthrall' crew members and enslave them.
They also burn in the light but heal rapidly whilst in the dark.
The game will end under two conditions:
    1. The shadowlings die
    2. The emergency shuttle docks at CentCom
